/**
 * @file domain/export/export_engine.js
 * @description Unified export logic for PDF, Markdown, and JSON.
 * Supports Strategic Report, Obsidian Vault export, and Scenario Comparisons.
 * @version 2.2.0 - Fix plan.zone → plan.zoneCode || plan.zone;
 *                  Add overlay flags, location score, effective buildable area,
 *                  and services info to both report generators.
 */

import { fmt, fmtM, pct } from '../../core/utils/formatters.js';

// ─────────────────────────────────────────────────────────────────────────────
// Internal helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Returns a canonical zone string from a planning object. */
const resolveZone = (plan) => (plan?.zoneCode || plan?.zone || 'N/A').trim();

/** Returns a compact overlay summary string, e.g. "HO, VPO, DDO". */
const activeOverlays = (plan) => {
  if (!plan) return 'None';
  const flags = [
    plan.hasHO   && 'HO',
    plan.hasVPO  && 'VPO',
    plan.hasSBO  && 'SBO',
    plan.hasBMO  && 'BMO',
    plan.hasDDO  && 'DDO',
    plan.hasSLO  && 'SLO',
    plan.hasESO  && 'ESO',
    plan.hasACHO && 'ACHO',
    plan.hasEMO  && 'EMO',
  ].filter(Boolean);
  if (plan.hasSingleCovenant) flags.push('Single Dwelling Covenant');
  if (plan.hasS173)           flags.push('S.173 Agreement');
  if (plan.hasEasementBoe)    flags.push('Easement (BOE)');
  return flags.length > 0 ? flags.join(', ') : 'None';
};

/** Returns a compact services string. */
const servicesLine = (plan) => {
  if (!plan) return 'N/A';
  const s = [
    plan.servicesElec  && 'Electricity',
    plan.servicesGas   && 'Gas',
    plan.servicesWater && 'Water',
    plan.servicesSewer && 'Sewer',
  ].filter(Boolean);
  return s.length > 0 ? s.join(', ') : 'Not confirmed';
};

// ─────────────────────────────────────────────────────────────────────────────
// Strategic Report (Markdown)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generates a high-level strategic report in Markdown format.
 */
export const generateStrategicReport = (state, calculations, insights = null) => {
  const { site, plan, finance } = state;
  const isoDate = new Date().toISOString().slice(0, 10);
  const d       = new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' });
  const addr    = (site?.address || 'Address not entered').trim();
  const zone    = resolveZone(plan);

  const margin = calculations?.margin || 0;
  const rating = margin >= 20 ? 'HIGHLY VIABLE' : margin >= 15 ? 'VIABLE' : margin >= 10 ? 'MARGINAL' : 'RISKY';

  // Location score from store investigation path
  const locScore = site?.investigation?.locationData?.score;
  const locRating = locScore != null ? `${locScore}/100` : 'Not analysed';

  // Effective buildable area from synthesis
  const effectiveArea = site?.investigation?.synthesis?.effectiveArea;
  const effectiveAreaStr = effectiveArea != null ? `${effectiveArea} m²` : 'Not calculated';

  return [
    `---`,
    `project: "${addr}"`,
    `date: ${isoDate}`,
    `rating: ${rating}`,
    `margin: ${pct(margin)}`,
    `---`,
    ``,
    `# Project Feasibility Report: ${addr}`,
    `**Date:** ${d} | **Status:** ${rating}`,
    `*Generated by WebTool SaaS Strategic Engine*`,
    ``,
    `---`,
    `## 1. Executive Summary`,
    `The project at ${addr} is currently rated as **${rating}**.`,
    `The projected Net Profit is **${fmt(calculations?.profit || 0)}** with a margin of **${pct(margin)}**.`,
    ``,
    `## 2. Financial Snapshot`,
    `| Metric | Value |`,
    `| :--- | :--- |`,
    `| Gross Realization Value (GRV) | ${fmt(calculations?.grv || 0)} |`,
    `| Total Development Cost (TDC) | ${fmt(calculations?.total || 0)} |`,
    `| Capitalized Interest | ${fmt(calculations?.capInterest || 0)} |`,
    `| Net Profit | ${fmt(calculations?.profit || 0)} |`,
    `| Project Margin | ${pct(margin)} |`,
    `| Estimated IRR | ${calculations?.irr?.toFixed(2) || '0.00'}% |`,
    `| Land Acquisition Cost | ${fmt(calculations?.land || 0)} |`,
    ``,
    `## 3. Site & Planning`,
    `| Attribute | Value |`,
    `| :--- | :--- |`,
    `| Zone | ${zone} |`,
    `| Site Area | ${site?.area || 0} m² |`,
    `| Frontage | ${site?.frontage || 0} m |`,
    `| Depth | ${site?.depth || 0} m |`,
    `| Effective Buildable Area | ${effectiveAreaStr} |`,
    `| Build Area | ${finance?.buildArea || 0} m² |`,
    `| Build Cost | $${finance?.buildCostPSM || 0}/m² |`,
    `| Active Overlays | ${activeOverlays(plan)} |`,
    `| Covenants / Agreements | ${plan?.hasSingleCovenant ? 'Single Dwelling Covenant' : plan?.hasS173 ? 'S.173 Agreement' : 'None detected'} |`,
    `| Site Services | ${servicesLine(plan)} |`,
    ``,
    `## 4. Location Score`,
    `| Metric | Value |`,
    `| :--- | :--- |`,
    `| Overall Score | ${locRating} |`,
    locScore != null && site?.investigation?.locationData?.breakdown
      ? Object.entries(site.investigation.locationData.breakdown || {})
          .map(([k, v]) => `| ${k.charAt(0).toUpperCase() + k.slice(1)} | ${v?.score ?? '-'}/${v?.max ?? '-'} pts |`)
          .join('\n')
      : `| Detail | Run Site Investigation to generate location score |`,
    ``,
    `## 5. Funding & Drawdown (S-Curve Model)`,
    `The project utilizes a dynamic S-Curve funding model for capitalized interest calculation.`,
    `\`\`\``,
    (calculations?.drawdownSchedule || []).slice(0, 6).map(item =>
      `| Month ${item.month} | Drawdown: ${fmt(item.amount)} | Cumulative: ${fmt(item.cumulative)} |`
    ).join('\n') || '*No drawdown schedule available*',
    `\`\`\``,
    `*${calculations?.drawdownSchedule?.length > 6 ? `(Showing first 6 of ${calculations.drawdownSchedule.length} months)` : ''}*`,
    ``,
    `## 6. Strategic AI Insights`,
    insights
      ? `### Risk Assessment: ${insights.riskLevel}`
        + `\n- **Reason:** ${insights.riskReason}`
        + `\n- **Critical Red Flag:** ${insights.redFlag}`
        + `\n- **Opportunity:** ${insights.opportunity}`
        + `\n- **Recommendation:** ${insights.recommendation}`
      : `*AI Insights not generated for this project.*`,
    ``,
    `---`,
    `*End of Strategic Report*`,
  ].join('\n');
};

// ─────────────────────────────────────────────────────────────────────────────
// Obsidian MD export
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generates a property analysis note formatted for Obsidian vault ingestion.
 *
 * @param {Object} state        - Full store state
 * @param {Object} calculations - Output from calculateProjectFinances
 * @param {Object} insights     - AI insights object (optional)
 * @returns {string} Obsidian-compatible Markdown string
 */
export const generateObsidianMD = (state, calculations, insights = null) => {
  const scenario  = state?.scenarios?.[state?.system?.activeScenarioId] || {};
  const site      = scenario?.site      || {};
  const plan      = scenario?.planning  || {};
  const fin       = scenario?.finance   || {};
  const market    = scenario?.market    || {};
  const financing = scenario?.financing || {};

  const isoDate = new Date().toISOString().slice(0, 10);
  const addr    = (site?.address || 'Unknown Address').trim();
  const suburb  = addr.split(',')[1]?.trim() || 'Melbourne';
  const zone    = resolveZone(plan);

  const margin = calculations?.margin       || 0;
  const profit = calculations?.profit       || 0;
  const grv    = calculations?.grv          || 0;
  const total  = calculations?.total        || 0;
  const irr    = calculations?.irr          || 0;
  const capInt = calculations?.capInterest  || 0;

  const ratingTag = margin >= 20 ? 'prime'
    : margin >= 15 ? 'viable'
    : margin >= 10 ? 'marginal'
    : 'risky';

  const fatalRisks = scenario?.site?.investigation?.synthesis?.fatalRisks || [];
  const alerts     = scenario?.site?.investigation?.synthesis?.activeAlerts || [];
  const projMonths = fin?.projectMonths || 24;

  // Location score
  const locData   = site?.investigation?.locationData || {};
  const locScore  = locData?.score;
  const locBreak  = locData?.breakdown || {};

  // Spatial
  const effectiveArea = site?.investigation?.synthesis?.effectiveArea;

  const overlayStr  = activeOverlays(plan);
  const servicesStr = servicesLine(plan);

  const lines = [];

  // YAML Front Matter
  lines.push('---');
  lines.push(`title: "${addr}"`);
  lines.push(`date: ${isoDate}`);
  lines.push(`type: property-analysis`);
  lines.push(`status: ${ratingTag}`);
  lines.push(`zone: ${zone}`);
  lines.push(`suburb: "[[${suburb}]]"`);
  lines.push(`area_m2: ${site?.area || 0}`);
  lines.push(`frontage_m: ${site?.frontage || 0}`);
  lines.push(`land_price: ${fin?.landPrice || 0}`);
  lines.push(`grv: ${grv}`);
  lines.push(`tdc: ${total}`);
  lines.push(`margin_pct: ${margin.toFixed(2)}`);
  lines.push(`irr_pct: ${irr.toFixed ? irr.toFixed(2) : irr}`);
  lines.push(`cap_interest: ${capInt}`);
  lines.push(`project_months: ${projMonths}`);
  lines.push(`lvr_pct: ${financing?.lvrPct || 65}`);
  lines.push(`location_score: ${locScore != null ? locScore : 'N/A'}`);
  lines.push(`overlays: "${overlayStr}"`);
  lines.push(`tags: [property, feasibility, ${ratingTag}, ${zone.toLowerCase()}, ${suburb.toLowerCase().replace(/\s+/g, '-')}]`);
  lines.push('---');
  lines.push('');

  // Title block
  lines.push(`# ${addr}`);
  lines.push('');
  lines.push(`> [!info] Feasibility Rating: **${ratingTag.toUpperCase()}**`);
  lines.push(`> Margin: **${margin.toFixed(1)}%** | IRR: **${irr.toFixed ? irr.toFixed(1) : irr}%** | GRV: **${fmt(grv)}** | TDC: **${fmt(total)}**`);
  lines.push('');

  // Site Overview
  lines.push('## Site Overview');
  lines.push('');
  lines.push('| Attribute | Value |');
  lines.push('| :--- | :--- |');
  lines.push(`| Address | ${addr} |`);
  lines.push(`| Suburb | [[${suburb}]] |`);
  lines.push(`| Zone | [[${zone}]] |`);
  lines.push(`| Site Area | ${site?.area || 0} m² |`);
  lines.push(`| Frontage | ${site?.frontage || 0} m |`);
  lines.push(`| Depth | ${site?.depth || 0} m |`);
  lines.push(`| Effective Buildable Area | ${effectiveArea != null ? effectiveArea + ' m²' : 'Not calculated'} |`);
  lines.push('');

  // Planning & Constraints
  lines.push('## Planning & Constraints');
  lines.push('');
  lines.push('| Attribute | Value |');
  lines.push('| :--- | :--- |');
  lines.push(`| Zone | ${zone} |`);
  lines.push(`| Max Height | ${plan?.maxHeight || 'N/A'} m |`);
  lines.push(`| Min Lot Size | ${plan?.minLotSize || 'N/A'} m² |`);
  lines.push(`| Active Overlays | ${overlayStr} |`);
  lines.push(`| Covenants / S.173 | ${plan?.hasSingleCovenant ? '⚠️ Single Dwelling Covenant' : plan?.hasS173 ? '⚠️ S.173 Agreement' : 'None detected'} |`);
  lines.push(`| Site Services | ${servicesStr} |`);
  if (plan?.s173Details) lines.push(`| S.173 Details | ${plan.s173Details} |`);
  lines.push('');

  // Location Score
  if (locScore != null) {
    lines.push('## Location Score');
    lines.push('');
    lines.push(`**Overall: ${locScore}/100**`);
    lines.push('');
    lines.push('| Pillar | Score | Max |');
    lines.push('| :--- | :--- | :--- |');
    Object.entries(locBreak).forEach(([k, v]) => {
      const label = k.charAt(0).toUpperCase() + k.slice(1);
      lines.push(`| ${label} | ${v?.score ?? '-'} | ${v?.max ?? '-'} |`);
    });
    lines.push('');
  }

  // Financial Analysis
  lines.push('## Financial Analysis');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('| :--- | :--- |');
  lines.push(`| Land Price | ${fmt(fin?.landPrice || 0)} |`);
  lines.push(`| Gross Realisation Value | ${fmt(grv)} |`);
  lines.push(`| Total Development Cost | ${fmt(total)} |`);
  lines.push(`| Net Profit | ${fmt(profit)} |`);
  lines.push(`| Margin on Cost | ${margin.toFixed(2)}% |`);
  lines.push(`| Annualised IRR | ${irr.toFixed ? irr.toFixed(2) : irr}% |`);
  lines.push(`| Capitalised Interest | ${fmt(capInt)} |`);
  lines.push(`| Land Component | ${fmt(calculations?.land || 0)} |`);
  lines.push(`| Hard Costs | ${fmt(calculations?.hard || 0)} |`);
  lines.push(`| Soft Costs | ${fmt(calculations?.soft || 0)} |`);
  lines.push(`| Holding Costs | ${fmt(calculations?.hold || 0)} |`);
  lines.push('');

  // S-Curve Drawdown
  const schedule = calculations?.drawdownSchedule || [];
  if (schedule.length > 0) {
    lines.push('## Construction Drawdown (S-Curve)');
    lines.push('');
    lines.push('```');
    schedule.slice(0, 12).forEach(item => {
      const bar = '#'.repeat(Math.max(1, Math.round(item.weight * 30)));
      lines.push(`M${String(item.month).padStart(2, '0')} | ${bar.padEnd(30)} | ${fmt(item.amount)}`);
    });
    lines.push('```');
    lines.push('');
  }

  // Fatal Risks
  if (fatalRisks.length > 0) {
    lines.push('## Fatal Risks');
    lines.push('');
    fatalRisks.forEach(risk => {
      lines.push(`> [!danger] ${risk.item}`);
      lines.push(`> ${risk.message}`);
      lines.push('');
    });
  }

  // Active Alerts
  if (alerts.length > 0) {
    lines.push('## Active Alerts');
    lines.push('');
    alerts.forEach(alert => {
      const callout = alert.severity === 'critical' ? 'danger'
        : alert.severity === 'high' ? 'warning'
        : 'info';
      lines.push(`> [!${callout}] ${alert.label}`);
      lines.push(`> ${alert.message}`);
      lines.push('');
    });
  }

  // AI Insights (optional)
  if (insights) {
    lines.push('## AI Strategic Advisor');
    lines.push('');
    lines.push(`> [!tip] Risk Level: **${insights.riskLevel || 'N/A'}**`);
    lines.push(`> ${insights.riskReason || ''}`);
    lines.push('');
    if (insights.opportunity)    { lines.push(`**Opportunity:** ${insights.opportunity}`);       lines.push(''); }
    if (insights.recommendation) { lines.push(`**Recommendation:** ${insights.recommendation}`); lines.push(''); }
  }

  // Market Context
  lines.push('## Market Context');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('| :--- | :--- |');
  lines.push(`| GRV per Unit | ${fmt(market?.grvPerUnit || 0)} |`);
  lines.push(`| Number of Units | ${market?.grvUnits || 1} |`);
  lines.push(`| Days on Market (est.) | ${market?.dom || 45} |`);
  lines.push(`| Market Trend | ${market?.marketTrend || 'stable'} |`);
  lines.push('');

  lines.push('---');
  lines.push(`*Generated by WebTool SaaS Sovereign Engine - ${isoDate}*`);
  lines.push('');

  return lines.join('\n');
};

// ─────────────────────────────────────────────────────────────────────────────
// JSON backup
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Exports the current full state to a JSON string for backup or sharing.
 */
export const exportProjectJSON = (state) => {
  return JSON.stringify({
    ...state,
    exportDate: new Date().toISOString(),
    version: '2.2.0'
  }, null, 2);
};

// ─────────────────────────────────────────────────────────────────────────────
// PDF export
// ─────────────────────────────────────────────────────────────────────────────

// Lazy-load jsPDF from CDN on first use — avoids index.html dependency
const loadJsPDF = () => new Promise((resolve, reject) => {
  if (window.jspdf) return resolve(window.jspdf);
  const s = document.createElement('script');
  s.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
  s.onload  = () => resolve(window.jspdf);
  s.onerror = () => reject(new Error('Failed to load jsPDF from CDN'));
  document.head.appendChild(s);
});

export const exportToPDF = async (state, calculations) => {
  const scenario = state?.scenarios?.[state?.system?.activeScenarioId] || state;
  const site     = scenario?.site     || state?.site     || {};
  const plan     = scenario?.planning || state?.plan     || {};
  const fin      = scenario?.finance  || state?.finance  || {};

  const jspdfLib = await loadJsPDF();
  const { jsPDF } = jspdfLib;
  const doc = new jsPDF();

  const margin = calculations?.margin || 0;
  const rating = margin >= 20 ? 'HIGHLY VIABLE' : margin >= 15 ? 'VIABLE' : margin >= 10 ? 'MARGINAL' : 'RISKY';
  const zone   = resolveZone(plan);
  const addr   = site?.address || 'N/A';

  // Header
  doc.setFontSize(20);
  doc.setTextColor(40);
  doc.text('Project Feasibility Report', 10, 20);

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Site: ${addr}`, 10, 30);
  doc.text(`Zone: ${zone}  |  Status: ${rating}`, 10, 37);

  doc.setDrawColor(200);
  doc.line(10, 45, 200, 45);

  // Financial Summary
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text('Financial Summary', 10, 55);

  doc.setFontSize(11);
  doc.setTextColor(60);
  const metrics = [
    { label: 'Gross Realization Value (GRV)',    value: fmt(calculations?.grv || 0) },
    { label: 'Total Development Cost (TDC)',      value: fmt(calculations?.total || 0) },
    { label: 'Capitalized Interest (S-Curve)',    value: fmt(calculations?.capInterest || 0) },
    { label: 'Net Project Profit',                value: fmt(calculations?.profit || 0) },
    { label: 'Project Margin',                    value: `${margin.toFixed(2)}%` },
    { label: 'Estimated IRR',                     value: `${calculations?.irr?.toFixed(2) || '0.00'}%` },
  ];

  metrics.forEach((m, i) => {
    doc.text(`${m.label}:`, 15, 65 + (i * 8));
    doc.text(m.value, 160, 65 + (i * 8), { align: 'right' });
  });

  // Site & Planning
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text('Site & Planning', 10, 120);

  doc.setFontSize(11);
  doc.setTextColor(60);
  const siteRows = [
    { label: 'Zone',             value: zone },
    { label: 'Site Area',        value: `${site?.area || 0} m²` },
    { label: 'Frontage',         value: `${site?.frontage || 0} m` },
    { label: 'Build Area',       value: `${fin?.buildArea || 0} m²` },
    { label: 'Active Overlays',  value: activeOverlays(plan) },
    { label: 'Services',         value: servicesLine(plan) },
  ];
  siteRows.forEach((r, i) => {
    doc.text(`${r.label}:`, 15, 130 + (i * 7));
    doc.text(String(r.value), 160, 130 + (i * 7), { align: 'right' });
  });

  // Drawdown
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text('Funding Drawdown (First 6 Months)', 10, 180);
  doc.setFontSize(10);
  doc.setTextColor(60);

  (calculations?.drawdownSchedule || []).slice(0, 6).forEach((item, i) => {
    doc.text(`M${item.month} | ${fmt(item.amount)} | Cumulative: ${fmt(item.cumulative || 0)}`, 15, 190 + (i * 7));
  });

  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text('Generated by WebTool SaaS Sovereign Engine', 105, 280, { align: 'center' });

  return doc.save(`Feasibility_${addr}.pdf`);
};
