/**
 * @file domain/export/export_engine.js
 * @description Unified export logic for PDF, Markdown, and JSON.
 * Supports Strategic Report, Obsidian Vault export, and Scenario Comparisons.
 * @version 2.1.0 - Added generateObsidianMD with full property vault schema
 */

import { fmt, fmtM, pct } from '../../core/utils/formatters.js';

/**
 * Generates a high-level strategic report in Markdown format.
 */
export const generateStrategicReport = (state, calculations, insights = null) => {
  const { site, plan, finance } = state;
  const isoDate = new Date().toISOString().slice(0, 10);
  const d       = new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' });
  const addr    = (site?.address || 'Address not entered').trim();

  const margin = calculations?.margin || 0;
  const rating = margin >= 20 ? 'HIGHLY VIABLE' : margin >= 15 ? 'VIABLE' : margin >= 10 ? 'MARGINAL' : 'RISKY';

  return [
    `---`,
    `project: "${addr}"`,
    `date: ${isoDate}`,
    `rating: ${rating}`,
    `margin: ${pct(margin)}`,
    `---`,
    ``,
    `# Project Feasibility Report: ${addr}`,
    `**Date:** ${d} | **Status:** ${rating}`,
    `*Generated by WebTool SaaS Strategic Engine*`,
    ``,
    `---`,
    `## 1. Executive Summary`,
    `The project at ${addr} is currently rated as **${rating}**.`,
    `The projected Net Profit is **${fmt(calculations?.profit || 0)}** with a margin of **${pct(margin)}**.`,
    ``,
    `## 2. Financial Snapshot`,
    `| Metric | Value |`,
    `| :--- | :--- |`,
    `| Gross Realization Value (GRV) | ${fmt(calculations?.grv || 0)} |`,
    `| Total Development Cost (TDC) | ${fmt(calculations?.total || 0)} |`,
    `| Capitalized Interest | ${fmt(calculations?.capInterest || 0)} |`,
    `| Net Profit | ${fmt(calculations?.profit || 0)} |`,
    `| Project Margin | ${pct(margin)} |`,
    `| Estimated IRR | ${calculations?.irr?.toFixed(2) || '0.00'}% |`,
    `| Land Acquisition Cost | ${fmt(calculations?.land || 0)} |`,
    ``,
    `## 3. Funding & Drawdown (S-Curve Model)`,
    `The project utilizes a dynamic S-Curve funding model for capitalized interest calculation.`,
    `\`\`\``,
    (calculations?.drawdownSchedule || []).slice(0, 6).map(item =>
      `| Month ${item.month} | Drawdown: ${fmt(item.amount)} | Cumulative: ${fmt(item.cumulative)} |`
    ).join('\n') || '*No drawdown schedule available*',
    `\`\`\``,
    `*${calculations?.drawdownSchedule?.length > 6 ? `(Showing first 6 of ${calculations.drawdownSchedule.length} months)` : ''}*`,
    ``,
    `## 4. Strategic AI Insights`,
    insights
      ? `### Risk Assessment: ${insights.riskLevel}`
        + `\n- **Reason:** ${insights.riskReason}`
        + `\n- **Critical Red Flag:** ${insights.redFlag}`
        + `\n- **Opportunity:** ${insights.opportunity}`
        + `\n- **Recommendation:** ${insights.recommendation}`
      : `*AI Insights not generated for this project.*`,
    ``,
    `---`,
    `## 5. Project Parameters`,
    `- **Zoning:** ${plan?.zone || 'N/A'}`,
    `- **Site Area:** ${site?.area || 0} sqm`,
    `- **Build Area:** ${finance?.buildArea || 0} sqm`,
    `- **Build Cost:** $${finance?.buildCostPSM || 0}/sqm`,
    `---`,
    `*End of Strategic Report*`,
  ].join('\n');
};

/**
 * Generates a property analysis note formatted for Obsidian vault ingestion.
 *
 * Output follows the Obsidian YAML front matter standard with:
 *   - Dataview-compatible property fields
 *   - Wikilinks to zone and suburb pages
 *   - Callout blocks for risk signals
 *   - Tagged sections for search/filter
 *
 * @param {Object} state        - Full store state
 * @param {Object} calculations - Output from calculateProjectFinances
 * @param {Object} insights     - AI insights object (optional)
 * @returns {string} Obsidian-compatible Markdown string
 */
export const generateObsidianMD = (state, calculations, insights = null) => {
  const scenario  = state?.scenarios?.[state?.system?.activeScenarioId] || {};
  const site      = scenario?.site      || {};
  const plan      = scenario?.planning  || {};
  const fin       = scenario?.finance   || {};
  const market    = scenario?.market    || {};
  const financing = scenario?.financing || {};

  const isoDate = new Date().toISOString().slice(0, 10);
  const addr    = (site?.address || 'Unknown Address').trim();
  const suburb  = addr.split(',')[1]?.trim() || 'Melbourne';
  const zone    = plan?.zone || 'NRZ';

  const margin = calculations?.margin       || 0;
  const profit = calculations?.profit       || 0;
  const grv    = calculations?.grv          || 0;
  const total  = calculations?.total        || 0;
  const irr    = calculations?.irr          || 0;
  const capInt = calculations?.capInterest  || 0;

  const ratingTag = margin >= 20 ? 'prime'
    : margin >= 15 ? 'viable'
    : margin >= 10 ? 'marginal'
    : 'risky';

  const fatalRisks = scenario?.site?.investigation?.synthesis?.fatalRisks || [];
  const alerts     = scenario?.site?.investigation?.synthesis?.activeAlerts || [];
  const projMonths = fin?.projectMonths || scenario?.finance?.projectMonths || 24;

  const lines = [];

  // YAML Front Matter
  lines.push('---');
  lines.push(`title: "${addr}"`);
  lines.push(`date: ${isoDate}`);
  lines.push(`type: property-analysis`);
  lines.push(`status: ${ratingTag}`);
  lines.push(`zone: ${zone}`);
  lines.push(`suburb: "[[${suburb}]]"`);
  lines.push(`area_m2: ${site?.area || 0}`);
  lines.push(`frontage_m: ${site?.frontage || 0}`);
  lines.push(`land_price: ${fin?.landPrice || 0}`);
  lines.push(`grv: ${grv}`);
  lines.push(`tdc: ${total}`);
  lines.push(`margin_pct: ${margin.toFixed(2)}`);
  lines.push(`irr_pct: ${irr.toFixed ? irr.toFixed(2) : irr}`);
  lines.push(`cap_interest: ${capInt}`);
  lines.push(`project_months: ${projMonths}`);
  lines.push(`lvr_pct: ${financing?.lvrPct || 65}`);
  lines.push(`tags: [property, feasibility, ${ratingTag}, ${zone.toLowerCase()}, ${suburb.toLowerCase().replace(/\s+/g, '-')}]`);
  lines.push('---');
  lines.push('');

  // Title block
  lines.push(`# ${addr}`);
  lines.push('');
  lines.push(`> [!info] Feasibility Rating: **${ratingTag.toUpperCase()}**`);
  lines.push(`> Margin: **${margin.toFixed(1)}%** | IRR: **${irr.toFixed ? irr.toFixed(1) : irr}%** | GRV: **${fmt(grv)}** | TDC: **${fmt(total)}**`);
  lines.push('');

  // Site Overview
  lines.push('## Site Overview');
  lines.push('');
  lines.push('| Attribute | Value |');
  lines.push('| :--- | :--- |');
  lines.push(`| Address | ${addr} |`);
  lines.push(`| Suburb | [[${suburb}]] |`);
  lines.push(`| Zone | [[${zone}]] |`);
  lines.push(`| Site Area | ${site?.area || 0} m2 |`);
  lines.push(`| Frontage | ${site?.frontage || 0} m |`);
  lines.push(`| Depth | ${site?.depth || 0} m |`);
  lines.push('');

  // Financial Analysis
  lines.push('## Financial Analysis');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('| :--- | :--- |');
  lines.push(`| Land Price | ${fmt(fin?.landPrice || 0)} |`);
  lines.push(`| Gross Realisation Value | ${fmt(grv)} |`);
  lines.push(`| Total Development Cost | ${fmt(total)} |`);
  lines.push(`| Net Profit | ${fmt(profit)} |`);
  lines.push(`| Margin on Cost | ${margin.toFixed(2)}% |`);
  lines.push(`| Annualised IRR | ${irr.toFixed ? irr.toFixed(2) : irr}% |`);
  lines.push(`| Capitalised Interest | ${fmt(capInt)} |`);
  lines.push(`| Land Component | ${fmt(calculations?.land || 0)} |`);
  lines.push(`| Hard Costs | ${fmt(calculations?.hard || 0)} |`);
  lines.push(`| Soft Costs | ${fmt(calculations?.soft || 0)} |`);
  lines.push(`| Holding Costs | ${fmt(calculations?.hold || 0)} |`);
  lines.push('');

  // S-Curve Drawdown
  const schedule = calculations?.drawdownSchedule || [];
  if (schedule.length > 0) {
    lines.push('## Construction Drawdown (S-Curve)');
    lines.push('');
    lines.push('```');
    schedule.slice(0, 12).forEach(item => {
      const bar = '#'.repeat(Math.max(1, Math.round(item.weight * 30)));
      lines.push(`M${String(item.month).padStart(2, '0')} | ${bar.padEnd(30)} | ${fmt(item.amount)}`);
    });
    lines.push('```');
    lines.push('');
  }

  // Fatal Risks
  if (fatalRisks.length > 0) {
    lines.push('## Fatal Risks');
    lines.push('');
    fatalRisks.forEach(risk => {
      lines.push(`> [!danger] ${risk.item}`);
      lines.push(`> ${risk.message}`);
      lines.push('');
    });
  }

  // Active Alerts
  if (alerts.length > 0) {
    lines.push('## Active Alerts');
    lines.push('');
    alerts.forEach(alert => {
      const callout = alert.severity === 'critical' ? 'danger'
        : alert.severity === 'high' ? 'warning'
        : 'info';
      lines.push(`> [!${callout}] ${alert.label}`);
      lines.push(`> ${alert.message}`);
      lines.push('');
    });
  }

  // AI Insights (optional)
  if (insights) {
    lines.push('## AI Strategic Advisor');
    lines.push('');
    lines.push(`> [!tip] Risk Level: **${insights.riskLevel || 'N/A'}**`);
    lines.push(`> ${insights.riskReason || ''}`);
    lines.push('');
    if (insights.opportunity)    { lines.push(`**Opportunity:** ${insights.opportunity}`);       lines.push(''); }
    if (insights.recommendation) { lines.push(`**Recommendation:** ${insights.recommendation}`); lines.push(''); }
  }

  // Market Context
  lines.push('## Market Context');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('| :--- | :--- |');
  lines.push(`| GRV per Unit | ${fmt(market?.grvPerUnit || 0)} |`);
  lines.push(`| Number of Units | ${market?.grvUnits || 1} |`);
  lines.push(`| Days on Market (est.) | ${market?.dom || 45} |`);
  lines.push(`| Market Trend | ${market?.marketTrend || 'stable'} |`);
  lines.push('');

  lines.push('---');
  lines.push(`*Generated by WebTool SaaS Sovereign Engine - ${isoDate}*`);
  lines.push('');

  return lines.join('\n');
};

/**
 * Exports the current full state to a JSON string for backup or sharing.
 */
export const exportProjectJSON = (state) => {
  return JSON.stringify({
    ...state,
    exportDate: new Date().toISOString(),
    version: '2.1.0'
  }, null, 2);
};

/**
 * Professional PDF export wrapper.
 */
// Lazy-load jsPDF from CDN on first use — avoids index.html dependency
const loadJsPDF = () => new Promise((resolve, reject) => {
  if (window.jspdf) return resolve(window.jspdf);
  const s = document.createElement('script');
  s.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
  s.onload  = () => resolve(window.jspdf);
  s.onerror = () => reject(new Error('Failed to load jsPDF from CDN'));
  document.head.appendChild(s);
});

export const exportToPDF = async (state, calculations) => {
  const jspdfLib = await loadJsPDF();
  const { jsPDF } = jspdfLib;
  const doc = new jsPDF();

  const margin = calculations?.margin || 0;
  const rating = margin >= 20 ? 'HIGHLY VIABLE' : margin >= 15 ? 'VIABLE' : margin >= 10 ? 'MARGINAL' : 'RISKY';

  doc.setFontSize(20);
  doc.setTextColor(40);
  doc.text('Project Feasibility Report', 10, 20);

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Site: ${state.site?.address || 'N/A'}`, 10, 30);
  doc.text(`Status: ${rating}`, 10, 37);

  doc.setDrawColor(200);
  doc.line(10, 45, 200, 45);

  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text('Financial Summary', 10, 55);

  doc.setFontSize(11);
  doc.setTextColor(60);
  const metrics = [
    { label: 'Gross Realization Value (GRV)',    value: fmt(calculations?.grv || 0) },
    { label: 'Total Development Cost (TDC)',      value: fmt(calculations?.total || 0) },
    { label: 'Capitalized Interest (S-Curve)',    value: fmt(calculations?.capInterest || 0) },
    { label: 'Net Project Profit',                value: fmt(calculations?.profit || 0) },
    { label: 'Project Margin',                    value: `${margin.toFixed(2)}%` },
    { label: 'Estimated IRR',                     value: `${calculations?.irr?.toFixed(2) || '0.00'}%` },
  ];

  metrics.forEach((m, i) => {
    doc.text(`${m.label}:`, 15, 65 + (i * 8));
    doc.text(m.value, 120, 65 + (i * 8), { align: 'right' });
  });

  doc.setFontSize(14);
  doc.text('Funding Drawdown (Initial 6 Months)', 10, 120);
  doc.setFontSize(10);
  doc.text('Month | Drawdown Amount | Cumulative', 15, 130);
  doc.line(15, 132, 100, 132);

  (calculations?.drawdownSchedule || []).slice(0, 6).forEach((item, i) => {
    doc.text(`M${item.month} | ${fmt(item.amount)} | ${fmt(item.cumulative || 0)}`, 15, 140 + (i * 7));
  });

  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text('Generated by WebTool SaaS Sovereign Engine', 105, 280, { align: 'center' });

  return doc.save(`Professional_Report_${state.site?.address || 'Project'}.pdf`);
};
